import React, { useCallback, useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import SEOHead from '@components/SEOHead';
import NoAccess from '@components/NoAccess';
import { useAuth } from '../contexts/AuthContext';
import { getAuthToken } from '../utils/auth';
import { useGlobalUI } from '@components/GlobalUI';

const API_URL = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:3001';
const REGIONS = ['NA', 'EUW', 'EUNE', 'KR', 'JP', 'OCE', 'LAN', 'LAS', 'BR', 'RU'];
const RANKS = ['IRON', 'BRONZE', 'SILVER', 'GOLD', 'PLATINUM', 'EMERALD', 'DIAMOND', 'MASTER', 'GRANDMASTER', 'CHALLENGER', 'UNRANKED'];
const FORMATS = ['BO1', 'BO3', 'BO5', 'FEARLESS_BO1', 'FEARLESS_BO3', 'FEARLESS_BO5', 'BLOCK'];

type Identity = { id: string; teamId: string; name: string; tag: string | null; region: string; averageRank: string | null; averageDivision: string | null; averageLp: number | null; kind: 'profile' | 'team'; contactPreference?: string };
type Post = { id: string; teamId: string; teamName: string; teamTag: string | null; region: string; averageRank: string | null; averageDivision: string | null; averageLp: number | null; startTimeUtc: string; scrimFormat: string; details: string | null; status: string; proposalStats: { pendingCount: number; averageResponseMinutes: number | null }; myProposal: { status: string } | null };
type Proposal = { id: string; message: string | null; proposerTeam: { name: string; tag: string | null; region: string }; post: { teamId: string; startTimeUtc: string; scrimFormat: string } };
type Series = { id: string; matchCode: string; scheduledAt: string; hostTeam: { name: string; tag: string | null }; guestTeam: { name: string; tag: string | null }; proposal: { post: { scrimFormat: string } } | null };

const fmt = (value: string) => new Date(value).toLocaleString(undefined, { weekday: 'short', hour: '2-digit', minute: '2-digit', month: 'short', day: 'numeric' });
const label = (identity: { name: string; tag: string | null }) => `${identity.name}${identity.tag ? ` · ${identity.tag}` : ''}`;
const rank = (entry: { averageRank: string | null; averageDivision?: string | null; averageLp?: number | null }) => entry.averageRank ? `${entry.averageRank}${entry.averageDivision ? ` ${entry.averageDivision}` : ''}${entry.averageLp ? ` · ${entry.averageLp} LP` : ''}` : 'Rank not set';
const formatLabel = (value: string) => value.replace('FEARLESS_', 'Fearless ').replace('_', ' ');

function ScrimsPage() {
  const { user, loading } = useAuth();
  const { showToast } = useGlobalUI();
  const [identities, setIdentities] = useState<Identity[]>([]);
  const [posts, setPosts] = useState<Post[]>([]);
  const [proposals, setProposals] = useState<Proposal[]>([]);
  const [series, setSeries] = useState<Series[]>([]);
  const [selectedId, setSelectedId] = useState('');
  const [region, setRegion] = useState('');
  const [fearless, setFearless] = useState('');
  const [loadingData, setLoadingData] = useState(true);
  const [profileOpen, setProfileOpen] = useState(false);
  const [availabilityOpen, setAvailabilityOpen] = useState(false);
  const [challengePost, setChallengePost] = useState<Post | null>(null);
  const [busy, setBusy] = useState(false);
  const [profile, setProfile] = useState({ name: '', tag: '', region: 'EUW', averageRank: 'EMERALD', contactPreference: 'DISCORD' });
  const [availability, setAvailability] = useState({ startLocalTime: '', scrimFormat: 'FEARLESS_BO3', details: '' });
  const [message, setMessage] = useState('');

  const selected = identities.find((item) => item.id === selectedId) || identities[0] || null;
  const request = useCallback(async (path: string, init?: RequestInit) => {
    const token = await getAuthToken();
    const response = await fetch(`${API_URL}/api${path}`, { ...init, headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}`, ...(init?.headers || {}) } });
    const body = await response.json().catch(() => ({}));
    if (!response.ok) throw new Error(body.error || 'Something went wrong');
    return body;
  }, []);
  const load = useCallback(async () => {
    if (!user) return;
    setLoadingData(true);
    try {
      const query = new URLSearchParams(); if (region) query.set('region', region); if (fearless) query.set('fearless', fearless);
      const [identityData, postData, proposalData, seriesData] = await Promise.all([
        request('/scrims/identities'), request(`/scrims/posts?${query.toString()}`), request('/scrims/proposals/incoming'), request('/scrims/series/pending-results'),
      ]);
      const next = [...(identityData.profiles || []).map((item: any) => ({ ...item, kind: 'profile' })), ...(identityData.teams || []).map((item: any) => ({ ...item, teamId: item.id, kind: 'team' }))];
      setIdentities(next); setSelectedId((current) => next.some((item: Identity) => item.id === current) ? current : next[0]?.id || '');
      setPosts(postData.posts || []); setProposals(proposalData.proposals || []); setSeries(seriesData.series || []);
    } catch (error: any) { showToast(error.message || 'Could not load Scrims', 'error'); }
    finally { setLoadingData(false); }
  }, [fearless, region, request, showToast, user]);
  useEffect(() => { void load(); }, [load]);

  const createProfile = async (event: React.FormEvent) => { event.preventDefault(); setBusy(true); try { const result = await request('/scrims/profiles', { method: 'POST', body: JSON.stringify({ ...profile, defaultAverageRank: profile.averageRank, averageRank: undefined }) }); setProfileOpen(false); showToast('Scrim Profile created', 'success'); await load(); setSelectedId(result.profile?.id || ''); } catch (error: any) { showToast(error.message, 'error'); } finally { setBusy(false); } };
  const publish = async (event: React.FormEvent) => { event.preventDefault(); if (!selected) return; setBusy(true); try { await request('/scrims/posts', { method: 'POST', body: JSON.stringify({ teamId: selected.teamId, averageRank: selected.averageRank || 'UNRANKED', averageDivision: selected.averageDivision, averageLp: selected.averageLp, startTimeUtc: new Date(availability.startLocalTime).toISOString(), timezoneLabel: Intl.DateTimeFormat().resolvedOptions().timeZone, scrimFormat: availability.scrimFormat, details: availability.details }) }); setAvailabilityOpen(false); showToast('Availability is live', 'success'); await load(); } catch (error: any) { showToast(error.message, 'error'); } finally { setBusy(false); } };
  const challenge = async () => { if (!selected || !challengePost) return; setBusy(true); try { await request(`/scrims/posts/${challengePost.id}/proposals`, { method: 'POST', body: JSON.stringify({ proposerTeamId: selected.teamId, message }) }); setChallengePost(null); setMessage(''); showToast('Challenge sent', 'success'); await load(); } catch (error: any) { showToast(error.message, 'error'); } finally { setBusy(false); } };
  const decide = async (id: string, action: string) => { setBusy(true); try { await request(`/scrims/proposals/${id}/decision`, { method: 'PATCH', body: JSON.stringify({ action }) }); showToast(action === 'ACCEPT' ? 'Scrim confirmed' : action === 'DELAY' ? 'Kept as a backup' : 'Proposal passed', 'success'); await load(); } catch (error: any) { showToast(error.message, 'error'); } finally { setBusy(false); } };
  const visiblePosts = useMemo(() => posts.filter((post) => post.teamId !== selected?.teamId), [posts, selected]);
  if (loading) return null;
  if (!user) return <NoAccess />;

  return <><SEOHead title="Scrim Finder | RiftEssence" description="Find a reliable League of Legends scrim." />
    <main className="min-h-screen px-4 py-8 md:px-8" style={{ background: 'var(--color-bg-primary)' }}>
      <div className="mx-auto max-w-7xl">
        <div className="mb-7 flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.18em]" style={{ color: 'var(--color-accent)' }}>Scrim Finder</p><h1 className="mt-2 text-3xl font-bold" style={{ color: 'var(--color-text-primary)' }}>Find a scrim, keep it simple.</h1><p className="mt-2 max-w-2xl text-sm" style={{ color: 'var(--color-text-secondary)' }}>Use a lightweight Scrim Profile or a full team. Every confirmed scrim keeps its room, record, and reciprocal review.</p></div><Link href="/teams/scrims" className="text-sm font-semibold" style={{ color: 'var(--color-accent)' }}>Open full scrim room →</Link></div>
        <section className="rounded-2xl border p-4 md:p-5" style={{ borderColor: 'var(--color-border)', background: 'var(--color-bg-secondary)' }}><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div className="flex items-center gap-3"><span className="h-2.5 w-2.5 rounded-full bg-emerald-400" /><div><p className="text-xs font-semibold uppercase tracking-wide" style={{ color: 'var(--color-text-secondary)' }}>Your scrim identity</p>{selected ? <><p className="font-bold" style={{ color: 'var(--color-text-primary)' }}>{label(selected)} <span className="ml-1 text-xs font-medium" style={{ color: 'var(--color-text-secondary)' }}>{selected.kind === 'profile' ? 'Scrim Profile' : 'Team'}</span></p><p className="text-xs" style={{ color: 'var(--color-text-secondary)' }}>{selected.region} · {rank(selected)} · available when you say so</p></> : <p className="font-semibold" style={{ color: 'var(--color-text-primary)' }}>No identity yet</p>}</div></div><div className="flex flex-wrap gap-2">{identities.length > 1 && <select value={selectedId} onChange={(e) => setSelectedId(e.target.value)} className="rounded-lg border px-3 py-2 text-sm" style={{ borderColor: 'var(--color-border)', background: 'var(--color-bg-tertiary)', color: 'var(--color-text-primary)' }}>{identities.map((item) => <option key={item.id} value={item.id}>{label(item)}</option>)}</select>}<button onClick={() => selected ? setAvailabilityOpen(true) : setProfileOpen(true)} className="rounded-lg px-4 py-2 text-sm font-bold text-white" style={{ background: 'linear-gradient(135deg, #2563EB, #1D4ED8)' }}>{selected ? 'Update availability' : 'Create Scrim Profile'}</button></div></div></section>
        <div className="mt-6 grid gap-6 xl:grid-cols-[minmax(0,1fr)_340px]"><section><div className="mb-3 flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-lg font-bold" style={{ color: 'var(--color-text-primary)' }}>Available opponents</h2><p className="text-xs" style={{ color: 'var(--color-text-secondary)' }}>Availability, rank, format, and response signals—nothing buried.</p></div><div className="flex gap-2"><select aria-label="Region" value={region} onChange={(e) => setRegion(e.target.value)} className="rounded-lg border px-2 py-1.5 text-xs" style={{ borderColor: 'var(--color-border)', background: 'var(--color-bg-secondary)', color: 'var(--color-text-primary)' }}><option value="">All regions</option>{REGIONS.map((value) => <option key={value}>{value}</option>)}</select><select aria-label="Format" value={fearless} onChange={(e) => setFearless(e.target.value)} className="rounded-lg border px-2 py-1.5 text-xs" style={{ borderColor: 'var(--color-border)', background: 'var(--color-bg-secondary)', color: 'var(--color-text-primary)' }}><option value="">All formats</option><option value="FEARLESS">Fearless</option><option value="REGULAR">Regular</option></select></div></div>
          <div className="overflow-hidden rounded-2xl border" style={{ borderColor: 'var(--color-border)', background: 'var(--color-bg-secondary)' }}><div className="hidden grid-cols-[1.35fr_.8fr_.9fr_1fr_auto] gap-3 border-b px-5 py-3 text-[11px] font-bold uppercase tracking-wide md:grid" style={{ borderColor: 'var(--color-border)', color: 'var(--color-text-secondary)' }}><span>Opponent</span><span>Region / rank</span><span>Format</span><span>When</span><span /></div>{loadingData ? <p className="p-8 text-center text-sm" style={{ color: 'var(--color-text-secondary)' }}>Loading available scrims…</p> : visiblePosts.length === 0 ? <p className="p-8 text-center text-sm" style={{ color: 'var(--color-text-secondary)' }}>No active scrims match these filters.</p> : visiblePosts.map((post) => <article key={post.id} className="grid gap-3 border-b px-5 py-4 last:border-0 md:grid-cols-[1.35fr_.8fr_.9fr_1fr_auto] md:items-center" style={{ borderColor: 'var(--color-border)' }}><div><p className="font-bold" style={{ color: 'var(--color-text-primary)' }}>{post.teamName}{post.teamTag ? ` · ${post.teamTag}` : ''}</p><p className="mt-0.5 text-xs" style={{ color: 'var(--color-text-secondary)' }}>{post.proposalStats.averageResponseMinutes ? `Usually replies in ${post.proposalStats.averageResponseMinutes}m` : 'New on Scrim Finder'}{post.details ? ` · ${post.details}` : ''}</p></div><p className="text-sm" style={{ color: 'var(--color-text-primary)' }}>{post.region}<br /><span className="text-xs" style={{ color: 'var(--color-text-secondary)' }}>{rank(post)}</span></p><p className="text-sm font-semibold" style={{ color: 'var(--color-text-primary)' }}>{formatLabel(post.scrimFormat)}</p><p className="text-sm" style={{ color: 'var(--color-text-primary)' }}>{fmt(post.startTimeUtc)}</p><button disabled={!selected || Boolean(post.myProposal)} onClick={() => setChallengePost(post)} className="rounded-lg border px-3 py-2 text-sm font-bold disabled:opacity-50" style={{ borderColor: 'rgba(59,130,246,.65)', color: '#93C5FD' }}>{post.myProposal ? 'Sent' : 'Challenge'}</button></article>)}</div></section>
          <aside className="space-y-5"><section className="rounded-2xl border p-4" style={{ borderColor: 'var(--color-border)', background: 'var(--color-bg-secondary)' }}><h2 className="font-bold" style={{ color: 'var(--color-text-primary)' }}>My scrims</h2><p className="mt-1 text-xs" style={{ color: 'var(--color-text-secondary)' }}>Quick decisions stay visible and actionable.</p><div className="mt-4 space-y-3">{proposals.length === 0 ? <p className="text-sm" style={{ color: 'var(--color-text-secondary)' }}>No incoming challenges right now.</p> : proposals.slice(0, 3).map((proposal) => <div key={proposal.id} className="rounded-xl border p-3" style={{ borderColor: 'var(--color-border)', background: 'var(--color-bg-tertiary)' }}><p className="text-sm font-bold" style={{ color: 'var(--color-text-primary)' }}>{label(proposal.proposerTeam)}</p><p className="mt-1 text-xs" style={{ color: 'var(--color-text-secondary)' }}>{formatLabel(proposal.post.scrimFormat)} · {fmt(proposal.post.startTimeUtc)}</p>{proposal.message && <p className="mt-2 text-xs italic" style={{ color: 'var(--color-text-secondary)' }}>“{proposal.message}”</p>}<div className="mt-3 flex flex-wrap gap-2"><button disabled={busy} onClick={() => void decide(proposal.id, 'ACCEPT')} className="text-xs font-bold text-emerald-300">Accept</button><button disabled={busy} onClick={() => void decide(proposal.id, 'DELAY')} className="text-xs font-bold text-amber-300">Keep as backup</button><button disabled={busy} onClick={() => void decide(proposal.id, 'REJECT')} className="text-xs font-bold text-rose-300">Pass</button></div></div>)}</div></section><section className="rounded-2xl border p-4" style={{ borderColor: 'var(--color-border)', background: 'var(--color-bg-secondary)' }}><h2 className="font-bold" style={{ color: 'var(--color-text-primary)' }}>Active scrims</h2><div className="mt-3 space-y-3">{series.length === 0 ? <p className="text-sm" style={{ color: 'var(--color-text-secondary)' }}>Confirmed scrims will appear here with their match room.</p> : series.slice(0, 3).map((item) => <Link key={item.id} href="/teams/scrims" className="block rounded-xl border p-3" style={{ borderColor: 'var(--color-border)', background: 'var(--color-bg-tertiary)' }}><p className="text-sm font-bold" style={{ color: 'var(--color-text-primary)' }}>{label(item.hostTeam)} vs {label(item.guestTeam)}</p><p className="mt-1 text-xs" style={{ color: 'var(--color-text-secondary)' }}>{item.proposal?.post.scrimFormat || 'Scrim'} · {fmt(item.scheduledAt)}</p><p className="mt-2 font-mono text-xs text-blue-300">{item.matchCode}</p></Link>)}</div></section></aside></div>
      </div>
    </main>
    {profileOpen && <Modal title="Create a Scrim Profile" close={() => setProfileOpen(false)}><form onSubmit={createProfile} className="space-y-3"><p className="text-sm" style={{ color: 'var(--color-text-secondary)' }}>A quick identity for scrims. You can connect a full team later—nothing to set up first.</p><Text label="Profile name" value={profile.name} onChange={(value) => setProfile({ ...profile, name: value })} required /><Text label="Short tag (optional)" value={profile.tag} onChange={(value) => setProfile({ ...profile, tag: value })} /><Select label="Region" value={profile.region} onChange={(value) => setProfile({ ...profile, region: value })} values={REGIONS} /><Select label="Typical rank" value={profile.averageRank} onChange={(value) => setProfile({ ...profile, averageRank: value })} values={RANKS} /><Select label="Preferred contact" value={profile.contactPreference} onChange={(value) => setProfile({ ...profile, contactPreference: value })} values={['DISCORD', 'APP', 'EITHER']} /><Submit busy={busy}>Create profile</Submit></form></Modal>}
    {availabilityOpen && <Modal title="Update availability" close={() => setAvailabilityOpen(false)}><form onSubmit={publish} className="space-y-3"><p className="text-sm" style={{ color: 'var(--color-text-secondary)' }}>Publishing is available for Discord-linked profiles with scrim DMs enabled, so proposals have a reliable path back to you.</p><label className="block text-sm font-semibold" style={{ color: 'var(--color-text-primary)' }}>Start time<input required type="datetime-local" value={availability.startLocalTime} onChange={(e) => setAvailability({ ...availability, startLocalTime: e.target.value })} className="mt-1 block w-full rounded-lg border p-2" style={{ borderColor: 'var(--color-border)', background: 'var(--color-bg-tertiary)', color: 'var(--color-text-primary)' }} /></label><Select label="Format" value={availability.scrimFormat} onChange={(value) => setAvailability({ ...availability, scrimFormat: value })} values={FORMATS} /><Text label="Note (optional)" value={availability.details} onChange={(value) => setAvailability({ ...availability, details: value })} /><Submit busy={busy}>Publish availability</Submit></form></Modal>}
    {challengePost && <Modal title={`Challenge ${challengePost.teamName}`} close={() => setChallengePost(null)}><p className="text-sm" style={{ color: 'var(--color-text-secondary)' }}>You’ll propose as {selected ? label(selected) : 'your selected identity'} for {formatLabel(challengePost.scrimFormat)} at {fmt(challengePost.startTimeUtc)}.</p><label className="mt-4 block text-sm font-semibold" style={{ color: 'var(--color-text-primary)' }}>Message (optional)<textarea value={message} onChange={(e) => setMessage(e.target.value)} className="mt-1 block w-full rounded-lg border p-2" style={{ borderColor: 'var(--color-border)', background: 'var(--color-bg-tertiary)', color: 'var(--color-text-primary)' }} rows={3} /></label><div className="mt-4"><Submit busy={busy} onClick={challenge}>Send challenge</Submit></div></Modal>}
  </>;
}

function Modal({ title, close, children }: { title: string; close: () => void; children: React.ReactNode }) { return <div className="fixed inset-0 z-50 grid place-items-center bg-black/70 p-4"><section role="dialog" aria-modal="true" aria-label={title} className="w-full max-w-md rounded-2xl border p-5 shadow-2xl" style={{ borderColor: 'var(--color-border)', background: 'var(--color-bg-secondary)' }}><div className="mb-4 flex items-center justify-between"><h2 className="text-lg font-bold" style={{ color: 'var(--color-text-primary)' }}>{title}</h2><button onClick={close} className="text-sm" style={{ color: 'var(--color-text-secondary)' }}>Close</button></div>{children}</section></div>; }
function Text({ label, value, onChange, required }: { label: string; value: string; onChange: (value: string) => void; required?: boolean }) { return <label className="block text-sm font-semibold" style={{ color: 'var(--color-text-primary)' }}>{label}<input required={required} value={value} onChange={(e) => onChange(e.target.value)} className="mt-1 block w-full rounded-lg border p-2" style={{ borderColor: 'var(--color-border)', background: 'var(--color-bg-tertiary)', color: 'var(--color-text-primary)' }} /></label>; }
function Select({ label, value, onChange, values }: { label: string; value: string; onChange: (value: string) => void; values: string[] }) { return <label className="block text-sm font-semibold" style={{ color: 'var(--color-text-primary)' }}>{label}<select value={value} onChange={(e) => onChange(e.target.value)} className="mt-1 block w-full rounded-lg border p-2" style={{ borderColor: 'var(--color-border)', background: 'var(--color-bg-tertiary)', color: 'var(--color-text-primary)' }}>{values.map((item) => <option key={item} value={item}>{formatLabel(item)}</option>)}</select></label>; }
function Submit({ children, busy, onClick }: { children: React.ReactNode; busy: boolean; onClick?: () => void }) { return <button type={onClick ? 'button' : 'submit'} disabled={busy} onClick={onClick} className="w-full rounded-lg px-4 py-2.5 text-sm font-bold text-white disabled:opacity-50" style={{ background: 'linear-gradient(135deg, #2563EB, #1D4ED8)' }}>{busy ? 'Saving…' : children}</button>; }
export default ScrimsPage;
