ALTER TABLE "User"
  ADD COLUMN IF NOT EXISTS "unlockedCosmetics" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  ADD COLUMN IF NOT EXISTS "activeUsernameDecoration" TEXT,
  ADD COLUMN IF NOT EXISTS "activeHoverEffect" TEXT,
  ADD COLUMN IF NOT EXISTS "activeVisualEffect" TEXT,
  ADD COLUMN IF NOT EXISTS "activeNameplateFont" TEXT,
  ADD COLUMN IF NOT EXISTS "adCredits" INTEGER NOT NULL DEFAULT 0;

DO $$ BEGIN
  ALTER TYPE "WalletQuestKey" ADD VALUE IF NOT EXISTS 'ENABLE_DISCORD_DMS';
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
  ALTER TYPE "WalletQuestKey" ADD VALUE IF NOT EXISTS 'JOIN_SUPPORT_SERVER';
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;
