import Link from 'next/link';
import { LEGAL_VERSION } from '../utils/legalPolicy';
import { useLanguage } from '../contexts/LanguageContext';
import { useCookieConsent } from '../contexts/CookieConsentContext';

export const LEGAL_CONTACT_EMAIL = process.env.NEXT_PUBLIC_LEGAL_CONTACT_EMAIL || 'realthvlys@outlook.fr';
type Section = { title: string; paragraphs: string[] };
type DocumentKind = 'privacy' | 'cookies' | 'terms' | 'legal';

const documents: Record<'en' | 'fr', Record<DocumentKind, { title: string; intro: string; sections: Section[] }>> = {
  en: {
    privacy: {
      title: 'Privacy Policy',
      intro: 'This notice explains how Thomas BARTHOIS, the individual operator of RiftEssence, handles personal data during the beta. The GDPR and the French Data Protection Act apply. Acknowledging this notice does not consent to optional tracking.',
      sections: [
        { title: '1. Data and where it comes from', paragraphs: [
          'Account data includes your username, email when supplied, password hash, linked Discord identifier and username, session information, age range, and the version, language and time of your legal acceptance. We ask for an age range, not your date of birth or identity document. Required fields enable the account or requested feature; optional profile fields may be left blank.',
          'You provide profile details, languages, roles, champion collections, posts, guides, teams, community memberships, messages, ratings, media and support requests. Reports may include evidence links and an optional Discord contact. PE balances, rewards, purchases, refunds and ad campaigns produce transaction records.',
          'Discord and Riot supply the account information you authorize. Riot services supply game identifiers, rankings and statistics. Authorized Discord integrations can relay posts and ratings into the service. Technical requests expose IP addresses and browser information to the servers handling them. Ad measurement, when allowed, uses a hashed IP address and an account identifier when available; these are pseudonymous personal data, not anonymous data.',
        ] },
        { title: '2. Purposes and legal bases', paragraphs: [
          'Providing the account, requested integrations, messages, community features and PE transactions is based on performing the service contract (GDPR Article 6(1)(b)). Fraud prevention, account security, moderation and necessary diagnostics rely on legitimate interests (Article 6(1)(f)); you may object for reasons relating to your situation. Responding to applicable legal obligations relies on Article 6(1)(c).',
          'Optional audience measurement, advertising measurement and third-party media rely on your separate consent (Article 6(1)(a)). Refusal does not prevent account creation. Change or withdraw each choice through Cookie settings. Discord message forwarding is a separate account setting; enabling it sends message previews and relevant notifications to Discord. We do not sell personal data.',
        ] },
        { title: '3. Visibility, recipients and providers', paragraphs: [
          'Public profiles, posts, guides, shared collections, communities and ratings can be read by other people and may be indexed by search engines. Avoid publishing sensitive information or information about others without a lawful reason. Private messages are available to their participants; authorized moderators may access relevant records to investigate abuse. Report and bug-report details, including evidence links and contact details, may be forwarded to the restricted Discord channel used by the moderation team.',
          'The frontend is hosted by Vercel. During beta, Thomas BARTHOIS operates the backend on a personal server. Authorized administrators operate the service and its database. Cloudflare provides security and bot protection where enabled. Riot and Discord handle their respective integrations. Vercel Web Analytics is loaded only with audience-measurement consent. YouTube and externally hosted profile media load only with external-media consent; advertising images and measurement require ad-measurement consent.',
          'Some providers process data outside the European Economic Area, including in the United States. Provider-specific information and available contractual safeguards are linked below, including Vercel’s data-processing terms. Contact the operator for details of the safeguards applicable to a particular processing operation. An external website you deliberately visit has its own privacy rules.',
        ] },
        { title: '4. Retention and security', paragraphs: [
          'Account and integration data are kept while needed to provide your account and requested features, until removal or an erasure request is actioned. Public content remains until you remove it or it is removed through moderation. Messages, reports and evidence are retained while needed for their conversation, investigation or an associated dispute; continued retention must be justified by that purpose. Withdrawn provider access is no longer used.',
          'PE and campaign history is kept to operate balances, provide your dashboard and resolve transaction disputes. Any necessary legal or dispute records may be retained with restricted access after other account data is removed, only for the applicable legal period or duration of the dispute. Acceptance receipts remain associated with the account; they are not public. Operational diagnostic incidents are retained for 30 days and process-run records for 14 days. These limits do not describe separate hosting-provider logs or backups; ask the operator about those records.',
          'Access controls, password hashing, secure session cookies and transport security protect the service. No system provides absolute security. Do not submit passwords, identity documents or other unnecessary sensitive data as report evidence. Account erasure, backup erasure and deletion from third-party moderation records require handling across those systems; we will explain any necessary retention exception when responding to your request.',
        ] },
        { title: '5. Your rights and requests', paragraphs: [
          'You may request access, correction, erasure, restriction and, where applicable, portability, and object to processing based on legitimate interests. You can withdraw consent without affecting processing lawfully performed before withdrawal. French law also allows instructions concerning your data after death. Requests are free unless a lawful exception applies.',
          'Use the legal contact below, identifying your account and request. We may request proportionate verification if necessary, without routinely requiring an identity document. We respond within one month; complex requests may take up to two additional months, with an explanation within the first month. You may complain directly to the CNIL at cnil.fr or another competent supervisory authority.',
        ] },
        { title: '6. Minors and changes', paragraphs: [
          'Self-registration is available from age 15, with any legally required parental permission. If an account appears to belong to a younger child, contact us so we can restrict it and address the data involved. We do not request a full birth date. Parents or guardians may contact us to exercise applicable rights.',
          'Matching, rankings and game statistics help you browse the community; they do not make legal decisions about you. You can ask for a human review of a moderation decision. Material changes to these notices are presented for renewed acknowledgement with a new version. Optional tracking is never enabled by accepting revised terms.',
        ] },
      ],
    },
    cookies: {
      title: 'Cookie Policy',
      intro: 'These choices cover cookies, local storage and similar access to your device. Optional purposes are off until you choose them. Reject all and Accept all are available at the same level, and you may choose each optional purpose separately.',
      sections: [
        { title: '1. Necessary storage', paragraphs: [
          'The lfd_session cookie maintains authentication. It is HttpOnly, SameSite=Lax and Secure in production; its default lifetime is 12 hours, renewed through session activity as configured by the service. The local markers lfd_session_present and lfd_userId identify the current session in the interface until logout or browser-data removal. Legacy lfd_token data may be read for migration to cookie authentication and is cleared on logout.',
          'The riftessence_cookie_consent record stores your choices, policy version and timestamps for 180 days, whether you accept or refuse. It is necessary to remember your choice. Security and anti-bot services, including Cloudflare Turnstile on authentication forms, may process technical information needed to protect access.',
          'The theme, language and cursor preferences you request, draft forms, game progress, acknowledgement of interface notices and navigation state support those specific functions. They are not used for advertising or audience measurement. Local preferences and drafts remain until overwritten or cleared; session storage lasts for the browser session. Browser settings can remove or block this storage, which may prevent the corresponding function from working.',
        ] },
        { title: '2. Optional audience measurement', paragraphs: [
          'Vercel Web Analytics measures visits, viewed pages and technical usage information. It is disabled before consent, even where the provider describes its product as cookieless. Declining prevents the analytics script from loading. Withdrawing consent stops further collection and reloads the page to remove the active analytics runtime. Routine new-visitor notifications to Discord, and their visitor_tracked marker, have been retired.',
        ] },
        { title: '3. Optional ad measurement', paragraphs: [
          'Allowing this purpose loads advertisers’ externally hosted images and enables first-party impression and click measurement. Records contain the ad, placement, time, hashed IP address and account identifier if signed in. A hashed address is used to exclude repeat impressions from the same connection within one hour. Only eligible, consented views count against a campaign’s purchased budget.',
          'Without this choice, the site can still show an ad’s title and destination link, but does not load its external image or send impression/click measurements. Clicking a destination opens a separate website governed by its own choices. RiftEssence does not use cross-site behavioural advertising trackers.',
        ] },
        { title: '4. Optional external media', paragraphs: [
          'YouTube embeds and remotely hosted profile audio/backgrounds can contact other providers, disclose your IP address and allow those providers to access device information. They remain blocked until you allow external media. YouTube uses its privacy-enhanced embed domain, which does not replace consent. Media uploaded to RiftEssence and service assets needed to display the app are distinct from these third-party players.',
        ] },
        { title: '5. Change or withdraw your choices', paragraphs: [
          'Use Cookie settings in the footer or the button below at any time. Necessary purposes cannot be turned off in this panel; the optional switches are off by default. Closing a page, scrolling, registering and accepting the terms do not grant cookie consent.',
          'Choices apply to this browser and device for 180 days, then we ask again. Changes to the purposes may also require a new choice. Withdrawal disables the relevant integrations; the page reloads where necessary to stop already loaded services. A provider’s previously stored third-party cookies may also need to be removed through your browser settings. If storage is blocked, optional services remain off.',
        ] },
      ],
    },
    terms: {
      title: 'Terms of Service',
      intro: 'RiftEssence is a League of Legends community service operated in beta by Thomas BARTHOIS as an individual. These terms govern your account and use of the community features. They do not waive mandatory protections under French or European law.',
      sections: [
        { title: '1. Joining and accepting', paragraphs: [
          'You must be at least 15 to self-register, have capacity to agree to these terms and obtain a parent’s or legal guardian’s permission where required. Provide accurate account information and keep login credentials secure. Do not share, sell or impersonate another person’s account.',
          'Password registration requires an explicit agreement. If you authenticate through Discord or Riot, you must complete the legal review before using the account. An older account without a recorded acceptance must complete the same review. We record the document version and acceptance time. Reading the privacy and cookie notices is acknowledged separately from agreeing to optional processing. You may decline and sign out.',
        ] },
        { title: '2. Service and community rules', paragraphs: [
          'The service offers player discovery, teams, communities, coaching, guides, collections, messages, ratings, games, PE rewards and reviewed advertisements. Third-party integrations are subject to their own availability and rules. Beta features may change or be temporarily unavailable; changes must respect your applicable rights.',
          'Do not publish illegal material, threats, harassment, hate speech, sexual exploitation, scams, private personal information without a lawful reason, or content that infringes others’ rights. Do not manipulate ratings, impersonate users, automate reward farming, exploit vulnerabilities, distribute malware or send unsolicited promotional messages. Advertisements belong in the reviewed advertising service.',
        ] },
        { title: '3. Your content and reporting', paragraphs: [
          'You retain your rights in your content. You grant a non-exclusive, royalty-free permission to host, reproduce, technically adapt and display it only as needed to operate and share the features you request, for the period it remains on the service. This permission does not transfer ownership. Removal remains subject to justified legal preservation and copies legitimately made by other users.',
          'Use the reporting tools or legal contact to identify illegal content or abuse, with its precise location, reasons and relevant evidence. Do not submit evidence you have no right to share. Moderators may remove content, restrict features or suspend accounts in proportion to the issue. We provide reasons and a way to contest decisions where legally required, except where disclosure would undermine an investigation, security or a legal duty. Contact us for human review or a right-of-reply request.',
        ] },
        { title: '4. Prismatic Essence and advertisements', paragraphs: [
          'PE is a virtual service balance earned through platform activity and rewards. It is not money, a deposit or an investment, and cannot be withdrawn for cash. The current beta does not sell PE for euros. Rewards and purchases follow the rules and price shown before the action; technical corrections must not override mandatory user rights.',
          'Advertising costs 100 PE for 3 counted impressions, with a minimum of 500 PE for 15 impressions, in steps of 100 PE. Submission debits the balance. Staff review the creative; rejection refunds the PE in full. Approved campaigns run until their impression budget is spent, unless paused. Campaign dashboards show delivery and purchases.',
          'A counted view requires ad-measurement consent and at least half the ad being visible for one second. Repeated views from the same connection within one hour are excluded. Audience availability varies; impressions are not a promise of clicks, sales, unique people or delivery by a particular date. An advertiser must have the necessary rights to the creative and destination. Contact us about an interrupted campaign or disputed charge; no clause removes applicable statutory remedies.',
        ] },
        { title: '5. Availability, responsibility and external services', paragraphs: [
          'We take reasonable care to operate and secure the service. We do not guarantee uninterrupted access, a particular game result or the accuracy of every user’s contribution. You remain responsible for your conduct and content, subject to applicable law.',
          'Nothing excludes liability that cannot lawfully be excluded, including applicable consumer rights, mandatory digital-service guarantees, fraud or intentional wrongdoing. A third-party link does not mean we endorse its content. RiftEssence is not endorsed by Riot Games and does not reflect Riot Games’ views. League of Legends and Riot Games marks belong to their respective owners.',
        ] },
        { title: '6. Leaving, changes and disputes', paragraphs: [
          'You may stop using the service, remove available content or contact us to request account closure and data erasure. We explain any records that must lawfully be retained. Material changes to these terms require a new recorded acceptance before continued account use; they do not retroactively remove accrued rights.',
          'French law governs these terms, without depriving consumers of mandatory protections applicable in their country of habitual residence. Competent courts are determined by applicable law; no exclusive court or compulsory arbitration is imposed. Contact the operator first if you wish to seek an amicable resolution, without losing access to a court or regulator. Any future monetary commercial service will require appropriate operator details and transaction terms before it is offered.',
        ] },
      ],
    },
    legal: {
      title: 'Legal notice',
      intro: 'Publisher, publication director and data controller: Thomas BARTHOIS, individual operator of RiftEssence during its beta.',
      sections: [
        { title: 'Hosting', paragraphs: ['Frontend: Vercel Inc., 440 N Barranca Avenue #4133, Covina, CA 91723, United States. Provider contact and legal information: vercel.com/legal.', 'Backend: a personal server operated by Thomas BARTHOIS during the beta. Hosting details will be updated when the infrastructure changes.'] },
        { title: 'Contact and content notices', paragraphs: ['Use the contact below for privacy requests, legal notices, reports of illegal content or a right-of-reply request. Include the relevant URL, facts and a way to reply. Please avoid including unnecessary sensitive data. In-app reports can also be used for community content and technical issues.'] },
        { title: 'Status and intellectual property', paragraphs: ['RiftEssence is presented as an individual beta project; no incorporated company, registration number or commercial status is claimed here. The service name, code and original content are protected to the extent provided by law. User content and third-party trademarks remain their owners’ property.', 'RiftEssence is not endorsed by Riot Games. Vercel hosts the frontend; it does not operate the community or decide its moderation policies.'] },
      ],
    },
  },
  fr: {
    privacy: {
      title: 'Politique de confidentialité',
      intro: 'Cette notice explique comment Thomas BARTHOIS, éditeur individuel de RiftEssence, traite les données personnelles pendant la bêta. Le RGPD et la loi Informatique et Libertés s’appliquent. La prise de connaissance de cette notice ne vaut pas consentement aux traceurs facultatifs.',
      sections: [
        { title: '1. Données et sources', paragraphs: ['Les données de compte comprennent le pseudonyme, l’adresse électronique lorsqu’elle est fournie, l’empreinte du mot de passe, l’identifiant et le pseudonyme Discord associés, la session, la tranche d’âge et la version, la langue et la date de l’accord aux documents. Nous ne demandons ni date de naissance complète ni pièce d’identité à l’inscription. Les champs obligatoires servent au compte ou à la fonctionnalité demandée ; les champs facultatifs peuvent rester vides.', 'Vous fournissez les informations de profil, langues, rôles, collections, publications, guides, équipes, communautés, messages, évaluations, médias et demandes d’assistance. Les signalements peuvent contenir des liens de preuve et un contact Discord facultatif. Les soldes PE, récompenses, achats, remboursements et campagnes publicitaires génèrent un historique.', 'Discord et Riot transmettent les informations de compte autorisées ; Riot fournit aussi les identifiants de jeu, classements et statistiques. Des intégrations Discord autorisées peuvent relayer des publications et évaluations. Les serveurs reçoivent des informations techniques, dont l’adresse IP. Avec votre accord, la mesure publicitaire conserve une empreinte de l’IP et l’identifiant de compte lorsqu’il est disponible : ces données sont pseudonymisées, non anonymes.'] },
        { title: '2. Finalités et bases légales', paragraphs: ['Le compte, les intégrations demandées, messages, fonctions communautaires et opérations PE reposent sur l’exécution du contrat (article 6(1)(b) du RGPD). La prévention des abus, la sécurité, la modération et les diagnostics nécessaires reposent sur l’intérêt légitime (article 6(1)(f)), auquel vous pouvez vous opposer pour des raisons tenant à votre situation. Les obligations légales applicables reposent sur l’article 6(1)(c).', 'La mesure d’audience, la mesure publicitaire et les médias tiers facultatifs reposent sur votre consentement distinct (article 6(1)(a)). Les refuser n’empêche pas l’inscription. Vos choix restent modifiables via « Choix des cookies ». Le transfert des messages vers Discord est un réglage de compte séparé : son activation transmet des aperçus et notifications à Discord. Nous ne vendons pas vos données personnelles.'] },
        { title: '3. Visibilité, destinataires et transferts', paragraphs: ['Les profils, publications, guides, collections partagées, communautés et évaluations publics peuvent être consultés par d’autres personnes et indexés par les moteurs de recherche. Évitez les données sensibles ou les informations sur autrui sans raison licite. Les messages privés sont accessibles aux participants ; les modérateurs autorisés peuvent consulter les éléments nécessaires à une enquête. Les signalements, preuves et contacts fournis peuvent être transmis au canal Discord restreint de l’équipe.', 'Le frontend est hébergé par Vercel. Thomas BARTHOIS exploite le backend sur un serveur personnel pendant la bêta. Les administrateurs autorisés gèrent le service et sa base de données. Cloudflare assure la sécurité et la protection contre les robots lorsqu’elles sont activées. Riot et Discord interviennent pour leurs intégrations. Vercel Web Analytics est chargé uniquement après accord à la mesure d’audience. YouTube et les médias de profil externes nécessitent votre accord aux contenus externes ; les images et mesures publicitaires nécessitent l’accord correspondant.', 'Certains prestataires traitent des données hors de l’Espace économique européen, notamment aux États-Unis. Leurs informations et garanties contractuelles disponibles sont liées ci-dessous, dont les conditions de traitement de Vercel. Contactez l’éditeur pour connaître les garanties applicables à une opération donnée. Un site externe que vous choisissez de visiter applique ses propres règles.'] },
        { title: '4. Conservation et sécurité', paragraphs: ['Les données de compte et d’intégration sont conservées tant qu’elles sont nécessaires au compte et aux fonctions demandées, jusqu’à leur retrait ou au traitement d’une demande d’effacement. Les contenus publics subsistent jusqu’à leur suppression par vous ou la modération. Les messages, signalements et preuves sont conservés pour les besoins de la conversation, de l’enquête ou du litige associé ; leur conservation doit rester justifiée. Un accès révoqué auprès d’un fournisseur n’est plus utilisé.', 'L’historique PE et publicitaire sert à gérer les soldes, tableaux de bord et contestations. Les seules archives nécessaires à une obligation légale ou à un litige peuvent être conservées avec un accès restreint après effacement des autres données, pour la durée légale applicable ou celle du litige. Les reçus d’acceptation restent associés au compte et ne sont pas publics. Les incidents de diagnostic sont conservés 30 jours et les historiques d’exécution 14 jours. Ces délais ne décrivent pas les journaux et sauvegardes distincts des hébergeurs : contactez l’éditeur à leur sujet.', 'Les contrôles d’accès, l’empreinte des mots de passe, les cookies de session sécurisés et la sécurité du transport protègent le service, sans garantie absolue. N’envoyez pas de mots de passe ou documents sensibles inutiles comme preuves. L’effacement du compte, des sauvegardes et des copies de modération implique les systèmes concernés ; toute exception nécessaire sera expliquée lors de la réponse à votre demande.'] },
        { title: '5. Vos droits', paragraphs: ['Vous disposez de droits d’accès, rectification, effacement, limitation, portabilité lorsque applicable et opposition aux traitements fondés sur l’intérêt légitime. Vous pouvez retirer votre consentement sans remettre en cause les traitements antérieurs licites. Vous pouvez également définir des directives relatives à vos données après votre décès. L’exercice des droits est gratuit, sauf exception légale.', 'Écrivez au contact ci-dessous en identifiant le compte et la demande. Une vérification proportionnée peut être demandée si nécessaire, sans exiger systématiquement une pièce d’identité. Nous répondons sous un mois ; une demande complexe peut justifier deux mois supplémentaires, avec information dans le premier mois. Vous pouvez saisir directement la CNIL sur cnil.fr ou toute autre autorité compétente.'] },
        { title: '6. Mineurs et mises à jour', paragraphs: ['L’inscription autonome est proposée à partir de 15 ans, avec l’autorisation parentale requise par la loi. Signalez tout compte susceptible d’appartenir à un enfant plus jeune afin de permettre sa restriction et le traitement des données concernées. Aucune date de naissance complète n’est demandée. Les représentants légaux peuvent nous contacter pour exercer les droits applicables.', 'Les recommandations, classements et statistiques facilitent la navigation et ne prennent pas de décisions juridiques vous concernant. Une décision de modération peut faire l’objet d’une demande de réexamen humain. Toute modification substantielle des notices est présentée avec une nouvelle version. Accepter les nouvelles conditions n’active jamais les traceurs facultatifs.'] },
      ],
    },
    cookies: {
      title: 'Politique relative aux cookies',
      intro: 'Ces choix couvrent les cookies, le stockage local et les accès similaires au terminal. Les finalités facultatives sont désactivées avant votre choix. « Tout refuser » et « Tout accepter » sont proposés au même niveau ; chaque finalité peut être choisie séparément.',
      sections: [
        { title: '1. Stockage nécessaire', paragraphs: ['Le cookie lfd_session assure l’authentification. Il est HttpOnly, SameSite=Lax et Secure en production ; sa durée par défaut est de 12 heures, renouvelée par l’activité de session selon la configuration du service. Les marqueurs locaux lfd_session_present et lfd_userId identifient la session dans l’interface jusqu’à la déconnexion ou l’effacement du navigateur. L’ancien lfd_token peut être lu pour la migration vers les cookies et est effacé à la déconnexion.', 'riftessence_cookie_consent conserve les choix, la version et les dates pendant 180 jours, pour un accord comme pour un refus. Ce stockage est nécessaire pour respecter votre choix. Les dispositifs de sécurité, dont Cloudflare Turnstile sur les formulaires d’authentification, peuvent traiter les informations techniques nécessaires à la protection des accès.', 'Les préférences de thème, langue et curseur demandées, les brouillons, la progression des jeux, les avis d’interface masqués et l’état de navigation servent à ces seules fonctions. Ils ne servent ni à la publicité ni à la mesure d’audience. Les préférences et brouillons locaux restent jusqu’à leur remplacement ou effacement ; le stockage de session dure le temps de la session du navigateur. Les bloquer dans le navigateur peut empêcher la fonction correspondante.'] },
        { title: '2. Mesure d’audience facultative', paragraphs: ['Vercel Web Analytics mesure les visites, pages consultées et informations techniques d’utilisation. Il est désactivé avant consentement, même lorsque le fournisseur qualifie son produit de « sans cookies ». Le refus empêche le chargement du script ; le retrait bloque la collecte ultérieure et recharge la page pour arrêter le logiciel déjà chargé. Les notifications automatiques de nouveaux visiteurs vers Discord et le marqueur visitor_tracked ont été supprimés.'] },
        { title: '3. Mesure publicitaire facultative', paragraphs: ['Cette finalité permet de charger les images publicitaires externes et de compter les vues et clics dans RiftEssence. Les enregistrements comprennent la publicité, l’emplacement, la date, une empreinte de l’IP et l’identifiant de compte si connecté. L’empreinte évite les impressions répétées depuis la même connexion pendant une heure. Seules les vues éligibles avec consentement consomment le budget acheté.', 'Sans cet accord, le titre et le lien d’une publicité peuvent rester visibles, mais son image externe ne charge pas et aucune mesure de vue ou clic n’est envoyée. Ouvrir la destination conduit à un autre site avec ses propres règles. RiftEssence n’utilise pas de traceurs publicitaires comportementaux entre sites.'] },
        { title: '4. Contenus externes facultatifs', paragraphs: ['Les lecteurs YouTube et médias de profil hébergés à l’extérieur peuvent transmettre votre IP et permettre des accès au terminal par leurs fournisseurs. Ils restent bloqués avant votre accord. Le domaine YouTube de confidentialité renforcée ne remplace pas le consentement. Les médias téléversés sur RiftEssence et ressources nécessaires à l’affichage de l’application sont distincts de ces lecteurs tiers.'] },
        { title: '5. Modifier ou retirer votre accord', paragraphs: ['Ouvrez « Choix des cookies » en bas de page ou avec le bouton ci-dessous. Les finalités nécessaires ne se désactivent pas dans ce panneau ; les autres sont décochées par défaut. Fermer une page, défiler, s’inscrire ou accepter les conditions ne vaut pas consentement aux cookies.', 'Le choix s’applique à ce navigateur et cet appareil pendant 180 jours, puis il est redemandé. Un changement de finalité peut également nécessiter un nouveau choix. Le retrait désactive les intégrations concernées et recharge la page si nécessaire. Les cookies tiers antérieurement déposés peuvent aussi devoir être effacés via le navigateur. Si le stockage est bloqué, les services facultatifs restent désactivés.'] },
      ],
    },
    terms: {
      title: 'Conditions générales d’utilisation',
      intro: 'RiftEssence est un service communautaire League of Legends exploité en bêta par Thomas BARTHOIS à titre individuel. Ces conditions régissent le compte et les fonctions communautaires, sans écarter les protections impératives du droit français ou européen.',
      sections: [
        { title: '1. Inscription et acceptation', paragraphs: ['L’inscription autonome nécessite au moins 15 ans, la capacité d’accepter ces conditions et l’autorisation d’un représentant légal lorsqu’elle est requise. Fournissez des informations exactes et protégez vos identifiants. Le partage, la vente et l’usurpation de compte sont interdits.', 'L’inscription par mot de passe exige un accord explicite. Après authentification via Discord ou Riot, la revue des documents doit être complétée avant utilisation du compte. Les comptes antérieurs sans accord enregistré sont soumis à la même étape. La version et la date sont conservées. La prise de connaissance des politiques reste distincte de tout consentement facultatif. Vous pouvez refuser et vous déconnecter.'] },
        { title: '2. Service et règles de conduite', paragraphs: ['Le service propose recherche de joueurs, équipes, communautés, coaching, guides, collections, messages, évaluations, jeux, récompenses PE et publicités examinées. Les intégrations tierces dépendent de leurs propres règles et disponibilités. Les fonctionnalités bêta peuvent évoluer ou être temporairement indisponibles, dans le respect de vos droits.', 'Sont interdits les contenus illicites, menaces, harcèlement, haine, exploitation sexuelle, escroqueries, divulgation injustifiée de données privées et atteintes aux droits d’autrui. Ne manipulez pas les évaluations, n’usurpez pas d’identité, n’automatisez pas l’obtention de récompenses, n’exploitez pas de faille, ne diffusez pas de logiciel malveillant et n’envoyez pas de promotions non sollicitées. Les publicités passent par le service dédié.'] },
        { title: '3. Contenus et signalements', paragraphs: ['Vous conservez vos droits sur vos contenus. Vous accordez une autorisation non exclusive et gratuite de les héberger, reproduire, adapter techniquement et afficher uniquement pour les fonctions de publication et partage demandées, pendant leur présence sur le service. Aucun transfert de propriété n’en résulte. Le retrait tient compte des conservations légales justifiées et des copies légitimement réalisées par autrui.', 'Utilisez les outils de signalement ou le contact juridique, avec l’emplacement précis, les motifs et preuves pertinents. Ne transmettez pas de preuves que vous n’avez pas le droit de partager. La modération peut retirer un contenu, restreindre des fonctions ou suspendre un compte de façon proportionnée. Des motifs et une possibilité de contestation sont fournis lorsqu’exigés, sauf contrainte légale, de sécurité ou d’enquête. Contactez-nous pour un réexamen humain ou un droit de réponse.'] },
        { title: '4. Prismatic Essence et publicité', paragraphs: ['Les PE sont un solde virtuel gagné grâce à l’activité et aux récompenses du service, sans nature monétaire, de dépôt ou d’investissement, ni retrait en argent. La bêta actuelle ne vend pas de PE en euros. Les règles et prix sont affichés avant chaque action ; une correction technique ne peut écarter vos droits impératifs.', 'La publicité coûte 100 PE pour 3 impressions comptées, avec un minimum de 500 PE pour 15 impressions et des paliers de 100 PE. Le solde est débité à la soumission. L’équipe examine la création ; un rejet rembourse intégralement les PE. Une campagne approuvée continue jusqu’à épuisement du budget, sauf mise en pause. Le tableau de bord présente diffusion et achats.', 'Une vue comptée nécessite le consentement à la mesure publicitaire et au moins la moitié de la publicité visible pendant une seconde. Les répétitions depuis la même connexion pendant une heure sont exclues. Aucun nombre de clics, ventes, personnes uniques ou délai de diffusion n’est garanti. L’annonceur doit disposer des droits sur la création et la destination. Contactez-nous pour une campagne interrompue ou un débit contesté ; les recours légaux applicables restent ouverts.'] },
        { title: '5. Disponibilité et responsabilité', paragraphs: ['Nous apportons un soin raisonnable à l’exploitation et à la sécurité du service, sans garantir un accès ininterrompu, un résultat de jeu ou l’exactitude de toute contribution. Vous répondez de votre conduite et de vos contenus dans les conditions prévues par la loi.', 'Aucune clause n’exclut une responsabilité qui ne peut légalement l’être, notamment les droits des consommateurs, garanties impératives des services numériques, fraudes et fautes intentionnelles. Un lien externe ne vaut pas approbation. RiftEssence n’est pas approuvé par Riot Games et ne reflète pas ses opinions. Les marques League of Legends et Riot Games appartiennent à leurs titulaires.'] },
        { title: '6. Départ, modifications et litiges', paragraphs: ['Vous pouvez cesser l’utilisation, supprimer les contenus accessibles ou demander la fermeture et l’effacement du compte. Toute conservation légalement nécessaire est expliquée. Une modification substantielle des conditions nécessite un nouvel accord enregistré et ne supprime pas rétroactivement les droits acquis.', 'Le droit français s’applique sans priver les consommateurs des protections impératives de leur pays de résidence habituelle. Les juridictions compétentes sont celles prévues par la loi ; aucun tribunal exclusif ni arbitrage obligatoire n’est imposé. Une résolution amiable peut être recherchée auprès de l’éditeur sans empêcher la saisine d’un juge ou d’une autorité. Tout futur service commercial monétaire nécessitera les informations d’opérateur et conditions de transaction adaptées avant sa mise en place.'] },
      ],
    },
    legal: {
      title: 'Mentions légales',
      intro: 'Éditeur, directeur de la publication et responsable du traitement : Thomas BARTHOIS, exploitant individuel de RiftEssence pendant sa bêta.',
      sections: [
        { title: 'Hébergement', paragraphs: ['Frontend : Vercel Inc., 440 N Barranca Avenue #4133, Covina, CA 91723, États-Unis. Contact et informations du prestataire : vercel.com/legal.', 'Backend : serveur personnel exploité par Thomas BARTHOIS pendant la bêta. Les informations d’hébergement seront mises à jour lors d’un changement d’infrastructure.'] },
        { title: 'Contact et notifications', paragraphs: ['Utilisez le contact ci-dessous pour les droits sur vos données, notifications juridiques, contenus illicites ou demandes de droit de réponse. Précisez l’URL, les faits et un moyen de vous répondre, sans données sensibles inutiles. Les outils de signalement restent disponibles pour les contenus communautaires et incidents techniques.'] },
        { title: 'Statut et propriété intellectuelle', paragraphs: ['RiftEssence est présenté comme un projet bêta individuel ; aucune société immatriculée, aucun numéro d’enregistrement ou statut commercial n’est revendiqué ici. Le nom, le code et les contenus originaux sont protégés dans les limites légales. Les contributions et marques tierces restent la propriété de leurs titulaires.', 'RiftEssence n’est pas approuvé par Riot Games. Vercel héberge le frontend sans exploiter la communauté ni décider de sa modération.'] },
      ],
    },
  },
};

export default function LegalDocument({ kind }: { kind: DocumentKind }) {
  const { currentLanguage, setLanguage } = useLanguage();
  const { openSettings } = useCookieConsent();
  const locale = currentLanguage === 'fr' ? 'fr' : 'en';
  const doc = documents[locale][kind];
  return <main className="legal-page" lang={locale}>
    <header><Link href="/">{locale === 'fr' ? 'Accueil' : 'Home'}</Link><h1>{doc.title}</h1><p>{locale === 'fr' ? 'Version et date de mise à jour' : 'Version and last updated'}: {LEGAL_VERSION}</p><nav aria-label={locale === 'fr' ? 'Documents juridiques' : 'Legal documents'}>{(['terms', 'privacy', 'cookies', 'legal'] as const).map(key => <Link key={key} href={`/${key}`} aria-current={key === kind ? 'page' : undefined}>{documents[locale][key].title}</Link>)}</nav><button type="button" onClick={() => setLanguage(locale === 'fr' ? 'en' : 'fr')}>{locale === 'fr' ? 'Read in English' : 'Lire en français'}</button></header>
    <p>{doc.intro}</p>
    {doc.sections.map(section => <section key={section.title}><h2>{section.title}</h2>{section.paragraphs.map(paragraph => <p key={paragraph}>{paragraph}</p>)}</section>)}
    {kind === 'cookies' ? <button type="button" className="essence-button" onClick={openSettings}>{locale === 'fr' ? 'Choix des cookies' : 'Cookie settings'}</button> : null}
    <section><h2>{locale === 'fr' ? 'Contact de l’éditeur' : 'Operator contact'}</h2><p>Thomas BARTHOIS · RiftEssence</p>{LEGAL_CONTACT_EMAIL ? <p><a href={`mailto:${LEGAL_CONTACT_EMAIL}`}>{LEGAL_CONTACT_EMAIL}</a></p> : <p>{locale === 'fr' ? 'Contact électronique en cours de configuration. Utilisez le bouton de signalement pour joindre l’équipe pendant la bêta.' : 'Email contact is being configured. Use the report button to reach the team during beta.'}</p>}</section>
    <section><h2>{locale === 'fr' ? 'Informations complémentaires' : 'Further information'}</h2><ul>
      <li><a href="https://www.cnil.fr/fr/cookies-et-autres-traceurs/regles/cookies/comment-mettre-mon-site-web-en-conformite">CNIL — Cookies et traceurs</a></li>
      <li><a href="https://www.cnil.fr/fr/plaintes">CNIL — {locale === 'fr' ? 'Exercer vos droits et déposer une plainte' : 'Your rights and complaints'}</a></li>
      <li><a href="https://vercel.com/legal/privacy-notice">Vercel — Privacy notice</a> · <a href="https://vercel.com/legal/dpa">Data Processing Addendum</a></li>
      <li><a href="https://discord.com/privacy">Discord — Privacy</a> · <a href="https://www.riotgames.com/en/privacy-notice">Riot Games — Privacy</a></li>
      <li><a href="https://www.cloudflare.com/privacypolicy/">Cloudflare — Privacy</a> · <a href="https://policies.google.com/privacy">Google / YouTube — Privacy</a></li>
    </ul></section>
  </main>;
}
