DO $$ BEGIN
  ALTER TYPE "WalletQuestKey" ADD VALUE IF NOT EXISTS 'DAILY_SOCIAL_SPARK';
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
  ALTER TYPE "WalletQuestKey" ADD VALUE IF NOT EXISTS 'CREATE_FIRST_LFT_POST';
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
  ALTER TYPE "WalletQuestKey" ADD VALUE IF NOT EXISTS 'LINK_DISCORD_ACCOUNT';
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
  ALTER TYPE "WalletQuestKey" ADD VALUE IF NOT EXISTS 'RECEIVE_FIRST_FEEDBACK';
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
  ALTER TYPE "WalletQuestKey" ADD VALUE IF NOT EXISTS 'SEND_FIRST_CHAT_MESSAGE';
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;
