DO $$
BEGIN
  ALTER TYPE "ScrimFormat" ADD VALUE IF NOT EXISTS 'FEARLESS_BO1';
  ALTER TYPE "ScrimFormat" ADD VALUE IF NOT EXISTS 'FEARLESS_BO3';
  ALTER TYPE "ScrimFormat" ADD VALUE IF NOT EXISTS 'FEARLESS_BO5';
END $$;

ALTER TABLE "ScrimPost"
  ADD COLUMN IF NOT EXISTS "averageLp" INTEGER;
